name: ldar_sim_env
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=23.2.0
  - blosc=1.21.5
  - boto3=1.34.125
  - botocore=1.34.125
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - cads-api-client=1.0.3
  - cdsapi=0.7.0
  - certifi=2024.6.2
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - ephem=4.1.5
  - fonttools=4.53.0
  - freetype=2.12.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - intel-openmp=2024.1.0
  - jmespath=1.0.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=18.1.7
  - libcurl=8.8.0
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflang=5.0.0
  - libglib=2.80.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libogg=1.3.4
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvm-meta=5.0.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mkl=2024.1.0
  - msys2-conda-epoch=20160418
  - multiurl=0.3.1
  - munkres=1.1.4
  - netcdf4=1.6.5
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openmp=5.0.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.2.2
  - patsy=0.5.6
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.0
  - ply=3.11
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pyparsing=3.1.2
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - requests=2.32.3
  - s3transfer=0.10.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=70.0.0
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.0
  - sortedcontainers=2.4.0
  - statsmodels=0.14.2
  - tbb=2021.12.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6
