parameter_level: methods
version: "4.0"
method_name: OGI_FU
deployment_type: mobile
measurement_scale: component
sensor:
  type: OGI_camera_zim
  minimum_detection_limit: [0.24, 0.39] 
is_follow_up: True
cost:
  per_day: 0
  per_site: 500
time_between_sites:
  values: [30]
survey_time: 120
