parameter_level: methods
version: "4.0"
method_name: OGI
deployment_type: mobile
measurement_scale: component
sensor:
  type: OGI_camera_zim
is_follow_up: False
cost:
  per_day: 0
  per_site: 500
time_between_sites:
  values: [30]
surveys_per_year: 4
survey_time: 120
